// seed/seed.ts
export const visaInfo = [
  {
    id: 1,
    title: "Study Permit Basics",
    description: "A study permit is required for international students to study in Canada for over 6 months.",
    content: "To study in Canada for more than six months, international students must obtain a study permit. This document is issued by Immigration, Refugees and Citizenship Canada (IRCC) and requires a letter of acceptance from a Designated Learning Institution (DLI), proof of financial support, and a valid passport. The application process typically takes 4-12 weeks, so apply early! Be prepared to provide biometrics and possibly attend an interview. Once approved, you’ll receive a Port of Entry (POE) Letter of Introduction.",
    link: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html",
    university: "General",
    author: { name: "Emma Johnson", email: "emma@ish.com" },
    rating: { likes: 25, average: 4.5 },
  },
  {
    id: 2,
    title: "Work Permit Options",
    description: "Post-graduation work permits allow students to work in Canada after their studies.",
    content: "After completing your studies, a Post-Graduation Work Permit (PGWP) lets you work in Canada for up to 3 years, depending on your program length. Apply within 180 days of receiving your final marks, ensuring your study permit is still valid. You’ll need a transcript and an official letter from your school. This permit is open, meaning no job offer is required, giving you flexibility to explore career options across Canada.",
    link: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work.html",
    university: "General",
    author: { name: "Liam Patel", email: "liam@ish.com" },
    rating: { likes: 18, average: 4.2 },
  },
  {
    id: 3,
    title: "Navigating UofT’s Visa Process",
    description: "Tips for University of Toronto students applying for study permits.",
    content: "At the University of Toronto, international students should start their visa process by contacting the Centre for International Experience (CIE). You’ll need your acceptance letter, proof of funds (around $20,000 CAD/year), and a study plan. UofT offers workshops to guide you through IRCC forms. Expect delays during peak seasons (May-August), so apply by April for Fall admission. Use the UofT portal to track your application status.",
    link: "https://www.utoronto.ca/international-students",
    university: "University of Toronto",
    author: { name: "Sophia Chen", email: "sophia@ish.com" },
    rating: { likes: 30, average: 4.7 },
  },
  {
    id: 4,
    title: "Housing and Visas at UBC",
    description: "How UBC students can align visa applications with housing needs.",
    content: "The University of British Columbia (UBC) advises students to secure a study permit before applying for on-campus housing. You’ll need your permit number to book a residence spot. Off-campus options in Vancouver require a Temporary Resident Visa (TRV) or Electronic Travel Authorization (eTA) alongside your permit. UBC’s International Student Advising team can help with documentation—schedule an appointment early. Budget $15,000 CAD/year for living expenses.",
    link: "https://students.ubc.ca/international",
    university: "University of British Columbia",
    author: { name: "Noah Kim", email: "noah@ish.com" },
    rating: { likes: 22, average: 4.3 },
  },
  {
    id: 5,
    title: "McGill’s Guide to Co-op Work Permits",
    description: "Understanding co-op work permits for McGill University students.",
    content: "McGill’s co-op programs require a special Co-op Work Permit in addition to your study permit. Apply online via IRCC, submitting your co-op letter from McGill’s Career Planning Service (CaPS). Processing takes 3-5 weeks, and it’s free! Ensure your study permit conditions allow off-campus work. This permit is employer-specific, so update it if your placement changes. McGill hosts visa info sessions each semester—check the calendar!",
    link: "https://www.mcgill.ca/internationalstudents/work/co-op",
    university: "McGill University",
    author: { name: "Ava Rodriguez", email: "ava@ish.com" },
    rating: { likes: 15, average: 4.0 },
  },
  {
    id: 6,
    title: "Extending Your Stay in Canada",
    description: "Steps to extend your study permit before it expires.",
    content: "To extend your study permit, apply online at least 30 days before it expires through your IRCC account. You’ll need updated proof of enrollment, financial statements showing $10,000 CAD/year, and a letter explaining why you need more time. Processing can take 60-90 days, but you’re under implied status if applied on time. Check your permit’s conditions—some restrict extensions. Visit a local visa office for urgent cases.",
    link: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/extend-study-permit.html",
    university: "General",
    author: { name: "Ethan Lee", email: "ethan@ish.com" },
    rating: { likes: 20, average: 4.4 },
  },
  {
    id: 7,
    title: "UAlberta’s Visa Tips for Newcomers",
    description: "Visa advice tailored for University of Alberta students.",
    content: "New international students at the University of Alberta should prepare for their study permit by gathering a letter of acceptance, proof of $17,000 CAD/year, and a valid passport. UAlberta’s International Student Services (ISS) offers pre-arrival webinars. Apply online via IRCC, and expect 6-8 weeks for processing. If you’re transferring from another Canadian school, notify IRCC within 10 days. Bring extra copies of documents to orientation!",
    link: "https://www.ualberta.ca/international",
    university: "University of Alberta",
    author: { name: "Olivia Smith", email: "olivia@ish.com" },
    rating: { likes: 28, average: 4.6 },
  },
  {
    id: 8,
    title: "Health Insurance and Visas",
    description: "How visa status affects health coverage in Canada.",
    content: "Your study permit status ties into health insurance eligibility. Most provinces require international students to enroll in private plans (e.g., $600-$800 CAD/year in Ontario) unless covered by a university plan like UHIP. Apply for provincial health coverage if your permit exceeds 12 months—e.g., OHIP in Ontario takes 3 months to activate. Keep your permit valid to avoid coverage gaps. Some schools offer emergency insurance—check with your registrar!",
    link: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/health-care.html",
    university: "General",
    author: { name: "Mason Taylor", email: "mason@ish.com" },
    rating: { likes: 17, average: 4.1 },
  },
];

export const jobs = [
  {
    id: 1,
    title: "Part-Time Barista",
    company: "Tim Hortons",
    location: "Toronto, ON",
    type: "Part-Time",
    salary: "$16/hour",
    description: "Serve coffee and assist customers in a fast-paced environment.",
    contact: "hr.toronto@timhortons.ca",
    premium: false,
  },
  {
    id: 2,
    title: "Software Developer Intern",
    company: "TechCorp",
    location: "Vancouver, BC",
    type: "Internship",
    salary: "$25/hour",
    description: "Work on real projects with a skilled development team.",
    contact: "careers@techcorp.com",
    premium: true,
  },
  {
    id: 3,
    title: "Retail Assistant",
    company: "ShopCo",
    location: "Calgary, AB",
    type: "Part-Time",
    salary: "$15/hour",
    description: "Assist customers and manage inventory in a retail setting.",
    contact: "jobs@shopco.ca",
    premium: false,
  },
];

export const housing = [
  {
    id: 1,
    title: "Cozy Apartment Near UBC",
    location: "Vancouver, BC",
    rent: "$1200/month",
    description: "1-bedroom apartment, 10-minute walk to UBC campus.",
    contact: "landlord.van@gmail.com",
    premium: false,
  },
  {
    id: 2,
    title: "Shared House in Downtown Toronto",
    location: "Toronto, ON",
    rent: "$800/month",
    description: "Room in a shared house, close to public transit.",
    contact: "torontohousing@outlook.com",
    premium: true,
  },
  {
    id: 3,
    title: "Studio Near McGill",
    location: "Montreal, QC",
    rent: "$1000/month",
    description: "Quiet studio apartment, perfect for students.",
    contact: "mcgill.rentals@yahoo.com",
    premium: false,
  },
];